/********************************************************************
 * Automatically generated by ARUnit
 * Filename: ARUnit_DoorSensorAbstractionSWC_.c
 * Generated on: Wed Dec 14 13:23:27 EET
 ********************************************************************/

#include "string.h"
#include "ARUnit_DoorSensorAbstractionSWC.h"


extern const Rte_CDS_DoorSensorAbstractionSWC Rte_Instance_DoorSensorAbstractionSWC;
extern const Rte_CDS_DoorSensorAbstractionSWC * const Rte_Inst_DoorSensorAbstractionSWC;




DECLSPEC_EXPORT void ARUnit_IWrite_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(uint8 DoorState)
{
		(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value = DoorState;
}
DECLSPEC_EXPORT uint8* ARUnit_IWriteRef_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return &(Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
DECLSPEC_EXPORT uint8 ARUnit_IRead_DoorSensorAbstractionSWC_ReadDoorSensor_PP_SR_DoorState(void)
{
	return (Rte_Inst_DoorSensorAbstractionSWC)->ReadDoorSensor_PP_SR_DoorState->value;
}
DECLSPEC_EXPORT Std_ReturnType ARUnit_Trigger_DoorSensorAbstractionSWC_Led_Switch_runnable(uint8 LedState)
{
	return Led_Switch_runnable(LedState);
}


DECLSPEC_EXPORT void ARUnit_Trigger_DoorSensorAbstractionSWC_ReadDoorSensor_runnable(void)
{
	ReadDoorSensor_runnable();
}
